  // File generated by FlutterFire CLI.
  // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for web - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for macos - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.windows:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for windows - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGE0tuhBnbAuNQgqNr-GvGTbWf8EOVe4w',
    appId: '1:575575627122:android:2ced1f2e63cd5f9493f9eb',
    messagingSenderId: '575575627122',
    projectId: 'fir-1-d853d',
    storageBucket: 'fir-1-d853d.firebasestorage.app',
  );

    static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyCaWiu5iBUEXbH2bnnbKiv5cw_FYnnLkFY',
      appId: '1:703166424327:ios:4f452dae1eddaff066d1a2',
      messagingSenderId: '703166424327',
      projectId: 'food-delivery-applicatio-39ecd',
      storageBucket: 'food-delivery-applicatio-39ecd.appspot.com',
      iosBundleId: 'com.example.foodOrder',
    );
  }